name: Deploy to EC2

on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: 54.85.91.143  # EC2 instance's IP
        USER: ec2-user      # Replace with your EC2 instance's SSH username
      run: |
        # Save private key to a file
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # SSH into EC2 and pull latest Docker image and run it
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'ENDSSH'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker pull tbristol01/django-todolist:latest
          docker stop django-todolist || true
          docker rm django-todolist || true
          docker run -d -p 8000:8000 --name django-todolist tbristol01/django-todolist:latest
        ENDSSH
