name: Deploy to EC2

on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}  # EC2 instance's IP from secrets
      USER: ec2-user             # Replace with your EC2 instance's SSH username
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.HOST }} " 