name: Pre-Production Workflow

on: [push, pull_request]

jobs:
  
  run-tests:
    name: Django Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          echo "Application can be accessed at: http://${{ vars.HOST }}:8000/"
          