name: Pre-Production Workflow

on: [push, pull_request]

jobs:
  scanning:
    name: GitGuardian Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: GitGuardian/ggshield-action@v1.20.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: scanning
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: github/codeql-action/init@v2
        with:
          languages: "python,javascript"
      - uses: github/codeql-action/analyze@v2

  run-tests:
    name: Django Unit Tests
    runs-on: ubuntu-latest
    needs: [scanning, static-code-analysis]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          echo "Application can be accessed at: http://${{ vars.HOST }}:8000/"
          