name: Docker Build

on:
    workflow_run:
      workflows: ["GitGuardian scan"]
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-django-app .
      # Replace "my-django-app" with your desired image name

