name: Combined Workflow

on: [push, pull_request]

jobs:
  scanning:
    name: GitGuardian Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        id: gitguardian
        uses: GitGuardian/ggshield-action@v1.20.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      
      - name: Display GitGuardian Scan Result
        run: |
          if [ ${{ steps.gitguardian.outputs.success }} == 'true' ]; then
            echo "GitGuardian scan succeeded."
          else
            echo "GitGuardian scan failed."
            exit 1
          fi

  build:
    name: Docker Build 
    runs-on: ubuntu-latest
    needs: scanning
    if: ${{ always() && needs.scanning.result == 'success' }} # Only execute if the "GitGuardian Scan" job was successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-django-app .
        # Replace "my-django-app" with your desired image name

      - name: Display Docker Build Result
        run: |
          if [ $? -eq 0 ]; then
            echo "Docker image build succeeded."
          else
            echo "Docker image build failed."
            exit 1
          fi

      - name: Armo Image Vulnerability Scan
        if: success() # Only run if the Docker image build was successful
        run: |
          # Install the Armo CLI tool (make sure you have the CLI tool and appropriate authentication set up)
          curl -s https://get.armo.io | bash
          # Replace with the command to run the Armo image vulnerability scan
          # Example: armo scan my-django-app:latest
          armo scan my-django-app:latest

      - name: Display Armo Scan Result
        if: success() # Only display if the Armo image vulnerability scan was successful
        run: |
          # Replace with the command to display the Armo scan results
          # Example: armo results
          echo "Armo image vulnerability scan succeeded."