name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  task1:
    name: Dockerize the Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-django-app .
        # Replace "my-django-app" with your desired image name

  task2:
    name: Test and Build Docker Container
    runs-on: ubuntu-latest
    needs: task1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          # Add commands to run your unit tests here
          echo "Running unit tests..."

      - name: Build Docker image
        run: docker build -t my-django-app .
        # Replace "my-django-app" with your desired image name

  task3:
    name: Provision AWS Infrastructure
    runs-on: ubuntu-latest
    needs: task2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Provision AWS Infrastructure
        run: |
          # Add commands to provision AWS infrastructure here
          echo "Provisioning AWS infrastructure..."

  task4:
    name: Deploy Dockerized Application
    runs-on: ubuntu-latest
    needs: task3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Dockerized Application
        run: |
          # Add commands to deploy the Dockerized application here
          echo "Deploying Dockerized application..."

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: task2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Static Code Analysis
        run: |
          # Add commands for static code analysis here
          echo "Running static code analysis...123"