name: Combined Workflow

on: [push, pull_request]

jobs:
  build:
    name: GitGuardian Scan, Docker Build, and Image Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: GitGuardian Scan
        id: gitguardian
        uses: GitGuardian/ggshield-action@v1.20.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      
      - name: Display GitGuardian Scan Result
        run: |
          if [ ${{ steps.gitguardian.outputs.success }} == 'true' ]; then
            echo "GitGuardian scan succeeded."
          else
            echo "GitGuardian scan failed."
            exit 1
          fi

      - name: Build Docker image
        id: docker_build
        run: docker build -t my-django-app .
        # Replace "my-django-app" with your desired image name

      - name: Display Docker Build Result
        run: |
          if [ ${{ steps.docker_build.exitcode }} -eq 0 ]; then
            echo "Docker image build succeeded."
          else
            echo "Docker image build failed."
            exit 1
          fi

      - name: Image Analysis for Vulnerabilities
        if: success() # Only run if the Docker image build was successful
        run: |
          # Run your vulnerability analysis tool on the built Docker image
          # Example: trivy my-django-app:latest
          echo "Running image vulnerability analysis..."
          # Ensure you have the vulnerability analysis tool installed
