name: Deploy and Dockerize

on:
  push:
    branches:
      - dev

jobs:
  deploy_and_dockerize:
    name: Deploy to EC2 and Dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got access to EC2 and we will start the deploy.
              cd /home/ubuntu/<PROJECT_DIRECTORY> &&
              git checkout dev &&
              git fetch --all &&
              git reset --hard origin/dev &&
              git pull origin dev &&
              sudo npm i &&
              sudo npm run build &&
              sudo pm2 stop ./dist/index.js &&
              sudo pm2 start ./dist/index.js
              '

      - name: Set up Docker
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build Docker image
        run: docker build -t my-django-app .
        working-directory: ./path/to/your/django/app  # Replace with your Django app directory

      - name: Push Docker image to GitHub Container Registry (GHCR)
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker tag my-django-app ghcr.io/${{ github.repository_owner }}/my-django-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/my-django-app:${{ github.sha }}

      - name: Deploy Docker container to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got access to EC2 and we will deploy the Docker container.
              docker pull ghcr.io/${{ github.repository_owner }}/my-django-app:${{ github.sha }}
              docker stop my-django-app || true
              docker rm my-django-app || true
              docker run -d --name my-django-app -p 8000:8000 ghcr.io/${{ github.repository_owner }}/my-django-app:${{ github.sha }}
              '
