name: Deploy Docker Container to EC2

on:
  pull_request:
    branches:
      - main  # or whichever branch you want this action to run on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to EC2
      run: |
        # Assuming your EC2 instance has Docker installed
        # and you've added your GitHub runner's public key to EC2's authorized_keys
        # Replace 'your-ec2-ip' with the IP of your EC2 instance
        # Replace 'your-docker-image-name:tag' with your Docker image name and tag
        ssh -i ${{ secrets.AWS_SSH_KEY }} -o StrictHostKeyChecking=no ec2-user@your-ec2-ip "docker pull your-docker-image-name:tag && docker run -d your-docker-image-name:tag"
